name: CI
on:
  pull_request:
    branches: [devel]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: |
          npm ci
          npm run format:check
          npm test -- --coverage
        env:
          CI: true

